library:
  source-dirs: src
copyright: 2020 Diego Marmsoler
maintainer: d.marmsoler@exeter.ac.uk
dependencies:
- base >= 4.7 && < 5
name: solidity-evaluator
version: 0.1.0.0
author: Diego Marmsoler
github: dmarmsoler/solidity
license: BSD3
executables:
  solidity-evaluator:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - solidity-evaluator
default-extensions: TypeSynonymInstances, FlexibleInstances
description: Please see the README on GitHub at <https://github.com/githubuser/solidity#readme>